### ISSUE TITLE
How to disable / enable xhr mocking ?

### ISSUE THREAD

**Issue by 19emtuck** [Huddle/PhantomXHR#8]
I would like to use phantomxhr in some complex use cases where some xhr queries have to pass and some others have to be mocked. He's there a way to disable/enable xhr mocking in a casperjs step ?
Another achievement would to permit mock on declared url (or regexp)

var fake_case = null;

casperjs.on('page.initialized',function(){
    // we mock edition error
    fake_case = xhr.fake({
          url: /case\.php/,
          method:'get',
          status:500,
          responseBody:'HTTP 500 ERROR'
    });
});

casperjs.then(function(){
   facke_case.disable();   
});

// do stuff

casperjs.then(function(){
   facke_case.enable();   
});

**Comment by jamescryer** [comment]
https://github.com/Huddle/PhantomXHR/pull/10  adds a restore method
