### ISSUE TITLE
phantomxhr fails when using overrideMimeType method (aka sinon.js issue)

### ISSUE THREAD

**Issue by 19emtuck** [Huddle/PhantomXHR#9]
// overrideMimeType is not mocked see this issue
// https://github.com/cjohansen/Sinon.JS/issues/559
window.sinon.FakeXMLHttpRequest.prototype.overrideMimeType = function() {return;}

maybe, the same kind of workaround could be used ?

**Comment by jamescryer** [comment]
Fixed by https://github.com/Huddle/PhantomXHR/pull/10
